version: '3'
services:
  api:
    image: wilfongjt/api-hapi
    build:
      context: ./api-hapi
    #command: npm run dev
    #command: >
    #  bash -c "npm install"
    #    bash -c "npm install && npm run start"
    command: >
      bash -c "npm install && npm install nodemon && npm run dev"

    volumes:
      - ./api-hapi:/usr/src/app
    ports:
      - "3000:3000"
    environment:
      - LB_ENV=dev
      - NODE_ENV=development
    networks:
      - backend
    restart: always
networks:
  backend:
    driver: bridge
