# Handy commands:
# docker system prune -a    # remove all images and containers

version: '3'
services:
  api:
    image: wilfongjt/api-hapi

    build:
      context: ./api-hapi

    command: >
      bash -c "npm install && npm install nodemon && npm run dev"

    volumes:
      - ./api-hapi:/usr/src/app

    ports:
      - "3001:3001"

    #  dockerfile          | 3000       | 3000       | 3000      | 3001
    #  docke-comp          | 3000:3000  | 3000:3001  | 3001:3000 | 3001:3001
    #  api                 | 3000       | 3001       | 3001      | 3001
    #  http://0.0.0.0:3000 |  ok        | ok         | no        |
    #  http://0.0.0.0:3001 |  no        | no         | no        |
    environment:
      - NODE_ENV=development
      - LB_ENV=dev
      - LB_API_PORT=3001
      - LB_API_HOST=0.0.0.0

    networks:
      - backend

    restart: always

networks:
  backend:
    driver: bridge
